### ISSUE TITLE
What is the client version number?

### ISSUE THREAD

**Issue by ghost** [sergio-ivanuzzo/idewave-core#6]
What is the client version number?

**Comment by sergio-ivanuzzo** [comment]
thanks for the attention to my project. It's for 2.4.3

**Comment by ghost** [comment]
> thanks for the attention to my project. It's for 2.4.3
The client I am using is 2.4.3_8606. I can't enter when I choose the world server. Is the client incompatible?

**Comment by sergio-ivanuzzo** [comment]
make sure you are using actual version of the project. Also, please make sure, you correctly set WorldServer ip in config. The client version you are using is correct.
