### ISSUE TITLE
Irrelevant interaction with third party in the async application

### ISSUE THREAD

**Issue by Markel-Kaluhin** [sergio-ivanuzzo/idewave-core#7]
You can take any number of sessions from scoped session object, but all requests will be queued at the psycopg2 level. To avoid this you need to use an asynchronous client, such as aiopg or asyncpg. This way you can use SQLAlcgemy but only as a query builder and only if you’ll define your data model as a scalar model but not as a declarative.

https://github.com/sergio-ivanuzzo/idewave-core/blob/80786793236d70cb3affa16cdf1f241d8a07d7e5/DB/Connection/BaseConnection.py#L27

**Comment by sergio-ivanuzzo** [comment]
Thanks, @markel-kalugin for your comment! I will try to investigate this issue. In case, if you have some tips I will be grateful for them :)

**Comment by artemovie** [comment]
You can use GINO (built on top of SQLAlchemy) instead of pure SQLAlchemy and it will resolve all async issues

**Comment by Markel-Kaluhin** [comment]
> You can use GINO (built on top of SQLAlchemy) instead of pure SQLAlchemy and it will resolve all async issues

`GINO` is a good way but for very simple operations because it doesn't work with the declare model only with the scalar. In other words, you'll use `SQLAlchemy` only as a query builder, but you couldn't declare tables as the classes with references and work with the full of the object model as you did these lines:

https://github.com/sergio-ivanuzzo/idewave-core/blob/master/DB/BaseModel.py#L13-L14

**Comment by Markel-Kaluhin** [comment]
> Thanks, @markel-kalugin for your comment! I will try to investigate this issue. In case, if you have some tips I will be grateful for them :)

Shortly `Python` has a big problem with async `ORM`. A few months ago I've started to create async `ORM` adapter based on the `SQLAlchemy` and `GINO` for work with the full object model. I'm not sure I need `GINO` for that but I use it only as an async wrapper.
Hope after a few months I'll release something like my own solution or as a part of `GINO` and let you know. Maybe at that time, this issue will be actual.

**Comment by sergio-ivanuzzo** [comment]
@markel-kalugin yes, please, let me know about your solution.
